# Generated by Django 2.2 on 2019-04-20 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190420_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 20, 17, 36, 30, 481062)),
        ),
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 20, 17, 36, 30, 481062)),
        ),
    ]
