# Generated by Django 5.0.8 on 2024-12-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("udemy", "0002_auto_20190430_0006"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enroll",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
